### PR TITLE
Fix #88: Added Android custom properties/config to flavors

### LINKED ISSUE #88: Android other properties flavors
Hello @AngeloAvv 

There are way to make custom android properties? Like:

```groovy
flavor_name {
            dimension "my_dimension"
            applicationId "com.flavor"
            applicationIdSuffix ".flavor_name" <---- I NEDD THIS LINE
            versionNameSuffix "-flavor_name-prod" <---- I NEDD THIS LINE
            signingConfig flavorSigning.flavor_name <---- I NEDD THIS LINE
        }
```

Maybe the yml to generate this could be something this:

```yml
...
flavor_name
    android:
            applicationId: "com.flavor"
            customConfig:
                applicationIdSuffix:  "\".flavor_name\""
                versionNameSuffix: "\"-flavor_name-prod\""
                signingConfig: "flavorSigning.flavor_name"
```

Please, this really turn development of advanced properties in android more productive!

### PR DESCRIPTION
**Pull request by JonathanAJ**
This PR (Fix: #88) added enhancement of custom configs to android flavors, to make development more productive.

### CODE REVIEW

**Comment by JonathanAJ** [comment]
@AngeloAvv ?

**Comment by AngeloAvv** [comment]
Hi @JonathanAJ , thanks for your PR. I'm a little bit busy these days. I will close some issues and PRs in the next weeks. I'm not 100% sure about keeping your naming convention but it's not so important at the moment. What's important right now is you to write some tests to avoid future commits that won't break anything.

**Comment by JonathanAJ** [comment]
The official android name convention it's called "defaultConfig", so I thought that "customConfig" was a better name convention to android developers domain.
  
  Ok, I will write some tests. I ran the current tests and anything broke.

**Comment by JonathanAJ** [comment]
@AngeloAvv I wrote tests following your same pattern on the project with the examples in README.md file.

You can merge after review.

**Pull request merged**
